import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import type { Account, Invoice } from "@xplatform/shared-types";

/** Client-side statement generation — no backend endpoint, no server-side
 * rendering dependency. Good enough for a demo statement; a real deployment
 * would likely template this server-side for consistent print layout. */
export async function downloadInvoicePdf(invoice: Invoice, account: Account): Promise<void> {
  const doc = await PDFDocument.create();
  const page = doc.addPage([595, 842]); // A4 in points
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  const black = rgb(0.1, 0.1, 0.1);
  const grey = rgb(0.45, 0.45, 0.45);
  const brand = rgb(0.94, 0.35, 0);

  let y = 800;
  const left = 50;
  const right = 545;

  page.drawText("xBilling", { x: left, y, size: 20, font: bold, color: brand });
  page.drawText("Municipal Statement", { x: right - 140, y, size: 14, font, color: grey });
  y -= 34;
  page.drawLine({ start: { x: left, y }, end: { x: right, y }, thickness: 1, color: rgb(0.85, 0.85, 0.85) });
  y -= 26;

  const row = (label: string, value: string) => {
    page.drawText(label, { x: left, y, size: 10, font, color: grey });
    page.drawText(value, { x: left + 140, y, size: 10, font: bold, color: black });
    y -= 18;
  };

  row("Account Number", account.accountNumber);
  row("Account Holder", account.consumerName);
  row("Municipality", account.municipality);
  row("Billing Period", invoice.billingPeriod);
  row("Issue Date", invoice.issueDate);
  row("Due Date", invoice.dueDate);
  row("Invoice", invoice.id);

  y -= 12;
  page.drawLine({ start: { x: left, y }, end: { x: right, y }, thickness: 1, color: rgb(0.85, 0.85, 0.85) });
  y -= 22;

  page.drawText("Description", { x: left, y, size: 10, font: bold, color: grey });
  page.drawText("Qty", { x: 330, y, size: 10, font: bold, color: grey });
  page.drawText("Unit Price", { x: 400, y, size: 10, font: bold, color: grey });
  page.drawText("Amount", { x: 490, y, size: 10, font: bold, color: grey });
  y -= 16;
  page.drawLine({ start: { x: left, y }, end: { x: right, y }, thickness: 0.5, color: rgb(0.85, 0.85, 0.85) });
  y -= 16;

  for (const line of invoice.lines) {
    page.drawText(line.description, { x: left, y, size: 10, font, color: black });
    page.drawText(String(line.quantity), { x: 330, y, size: 10, font, color: black });
    page.drawText(`R ${line.unitPrice.toFixed(2)}`, { x: 400, y, size: 10, font, color: black });
    page.drawText(`R ${line.amount.toFixed(2)}`, { x: 490, y, size: 10, font, color: black });
    y -= 18;
  }

  y -= 8;
  page.drawLine({ start: { x: left, y }, end: { x: right, y }, thickness: 1, color: rgb(0.85, 0.85, 0.85) });
  y -= 24;

  page.drawText("Total Amount", { x: 400, y, size: 11, font: bold, color: black });
  page.drawText(`R ${invoice.totalAmount.toFixed(2)}`, { x: 490, y, size: 11, font: bold, color: black });
  y -= 18;
  page.drawText("Paid to Date", { x: 400, y, size: 10, font, color: grey });
  page.drawText(`R ${invoice.amountPaid.toFixed(2)}`, { x: 490, y, size: 10, font, color: grey });
  y -= 18;
  const balance = invoice.totalAmount - invoice.amountPaid;
  page.drawText("Balance Due", { x: 400, y, size: 11, font: bold, color: brand });
  page.drawText(`R ${balance.toFixed(2)}`, { x: 490, y, size: 11, font: bold, color: brand });

  page.drawText("Generated by xPlatform — not a tax invoice unless otherwise indicated.", {
    x: left,
    y: 40,
    size: 8,
    font,
    color: grey,
  });

  const bytes = await doc.save();
  const buffer = new ArrayBuffer(bytes.byteLength);
  new Uint8Array(buffer).set(bytes);
  const blob = new Blob([buffer], { type: "application/pdf" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `statement-${invoice.id}.pdf`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
